apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: eventmediators.events.kabanero.io
spec:
  group: events.kabanero.io
  names:
    kind: EventMediator
    listKind: EventMediatorList
    plural: eventmediators
    singular: eventmediator
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: EventMediator is the Schema for the eventmediators API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: EventMediatorSpec defines the desired state of EventMediator
          properties:
            createListener:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: boolean
            createRoute:
              type: boolean
            insecureListener:
              type: boolean
            mediations:
              description: mediations
              items:
                properties:
                  body:
                    items:
                      description: ' Valid combinations are:   1) assignment   2)
                        if and assignment   3) if and body   4) switch   5) if and
                        switch   TBD: switch and default'
                      properties:
                        =:
                          type: string
                        body:
                          items: {}
                          type: array
                        default:
                          items: {}
                          type: array
                        if:
                          type: string
                        switch:
                          items: {}
                          type: array
                      type: object
                    type: array
                  name:
                    type: string
                  selector:
                    properties:
                      repositoryType:
                        properties:
                          file:
                            type: string
                          newVariable:
                            type: string
                        required:
                        - file
                        - newVariable
                        type: object
                      urlPattern:
                        type: string
                    type: object
                  sendTo:
                    description: Input string `json:"input,omitempty"`
                    items:
                      type: string
                    type: array
                  variables:
                    description: local variables
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                        valueExpression:
                          type: string
                      required:
                      - name
                      type: object
                    type: array
                required:
                - name
                type: object
              type: array
            repositories:
              items:
                properties:
                  github:
                    properties:
                      secret:
                        type: string
                      webhookSecret:
                        type: string
                    type: object
                type: object
              type: array
            variables:
              description: global variables
              items:
                properties:
                  name:
                    type: string
                  value:
                    type: string
                  valueExpression:
                    type: string
                required:
                - name
                type: object
              type: array
          type: object
        status:
          description: EventMediatorStatus defines the observed state of EventMediator
          properties:
            summary:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  input:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                  message:
                    type: string
                  operation:
                    type: string
                  result:
                    type: string
                  time:
                    format: date-time
                    type: string
                required:
                - input
                - message
                - operation
                - result
                type: object
              type: array
          required:
          - summary
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
